module.exports = {
  content: ["./src/**/*.{js,jsx,ts,tsx}"],
  theme: {
    colors: {
      success: "#00C851",
      darkgray: "#262626",
      gray: "#DCDCDC",
      lightblue: "#F0F6FF",
      lightblue2: "#DBEAFF",
      lightblue3: "#EBF3FF",
      buttonblue: "#5790FF",
      darkblue1: "#70ABFF",
      darkblue2: "#3F84E5",
      yesgreendefault: "#6ee5dd",
      yesgreen: "#4ecdc4",
      noreddefault: "#ffc4c4",
      nored: "#ff6b6b",
      white: "#ffffff",
      black: "#000000",
      slate: "#94a3b8",
      progress: "#FBFBFF",
      slatebackground: "#64748b",
      background: "#E5E5E5",
      approve: "#4ECDC4",
      reject: "#FF4C4C",
      lightgold: "#FFFBE8",
      darkgold: "#FFD921",
      reviewercontrolbox1: "#E1FAF8",
      reviewercontrolbox1text: "#4ECDC4",
      reviewercontrolbox1border: "#4ECDC4",
      reviewercontrolbox2: "#E0EDFF",
      reviewercontrolbox2text: "#3F84E5",
      reviewercontrolbox2border: "#3F84E5", 
      reviewercontrolbox3: "#FFEDED",
      reviewercontrolbox3text: "#FF6B6B",
      reviewercontrolbox3border: "#FF6B6B",
      reviewercontrolbox4: "#FFF7CF",
      reviewercontrolbox4text: "#FFD921",
      reviewercontrolbox4border: "#FFD921",
      reviewercommentborder: "#DBB8D8",
      reviewercommentbackdrop: "#FCF7FC",
    },
    screens: {
      'sm': '640px',
      'md': '768px',
      'nm' : '810px',
      'lg': '1024px',
      'xl': '1280px',
      '2xl': '1536px',
      '3xl': '1600px',
    }
    
  },
  plugins: [],
};
